name: Pack beta packages

on:  workflow_dispatch


jobs:
  build:
    uses: creatorflow-io/shared-workflows/.github/workflows/shared-pack.yml@master
    with:
       Stage: beta
       JuiceRefVersion: 6.0.0
    secrets: inherit